### PR TITLE
pass parameters at once

### PR DESCRIPTION
**Pull request by marcosfnsc**
both the dnf and flatpak allow you to pass through several software parameters at once, as the dnf is called once to install several programs or remove several programs, this made it much faster, theoretically the same for flatpak, I didn’t test it with other software besides these

### CODE REVIEW

**Comment by realgrm** [comment]
## For dnf
Thanks, I used to use this implementation that you suggested.
But I decided to install one by one, even if takes longer, because if one package is not found, all of the packages of the list are not installed/ removed. 
  
Example: The package `pygobject3` in the list doesn't exist

But your suggestion made me research in the manual and there's the parameter `--skip-broken` that makes this work.

I'll accept for dnf, but I need you to add this change before.

## For flatpak
The same error occurs, but I couldn't find a parameter that fix this issue.

Example: Try to add `app.doesnt.exist` in the list

**Review by realgrm — APPROVED** [review]
Changes applied

**Comment by realgrm** [comment]
Never mind, I discover that I can make the changes myself.
If you know some way of implementing the same way to flatpak, I'll let this PR open until tomorrow, than I'll close.

**Comment by realgrm** [comment]
From my research, today is not available an option to handle this errors with flatpak, so I opened an issue:
https://github.com/flatpak/flatpak/issues/4063

**Comment by marcosfnsc** [comment]
I also researched and did not find something equivalent for flatpak

**Pull request merged**
